name: Release
run-name:  build release by ${{ github.actor }} ğŸš€
on:
  release:
    types: [created,published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64, arm, ppc64le, ppc64, s390x]
    steps:
      - run: echo "ğŸ‰ ç”± ${{ github.event_name }} äº‹ä»¶è§¦å‘"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ æ‰€å¤„ä½ç½® ${{ github.repository }} "
      - name: Upload
        uses: wangyoucao577/go-release-action@v1.30
        with:
          pre_command: pwd && ls
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: https://dl.google.com/go/go1.21.0.linux-amd64.tar.gz
          project_path: "./go"
      - run: echo "ğŸ ä»»åŠ¡çŠ¶æ€ ${{ job.status }}."
